apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-app-installer
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-app-installer-role
  namespace: {{ (index .Values "argo-cd").namespaceOverride | default "argocd" }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["create", "update", "patch", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-app-installer-rb
  namespace: {{ (index .Values "argo-cd").namespaceOverride | default "argocd" }}
subjects:
  - kind: ServiceAccount
    name: argo-app-installer
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: argo-app-installer-role
  apiGroup: rbac.authorization.k8s.io
