apiVersion: apps/v1
kind: Deployment
metadata:
  name: kurrentdb-operator
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: kurrentdb-operator
    app.kubernetes.io/instance: kurrentdb-operator
    app.kubernetes.io/component: kurrentdb-operator
    app.kubernetes.io/created-by: kurrent
    app.kubernetes.io/part-of: kurrentdb-operator
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        app.kubernetes.io/release-timestamp: "{{ now | date "20060102150405" }}"
        kubectl.kubernetes.io/default-container: controller
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: kurrentdb-operator
    spec:
      securityContext:
        runAsNonRoot: true
{{- if and .Values.operator.imageRepository (ne (.Values.operator.imageRepository.credentialsSecretName | default "") "") }}
      imagePullSecrets:
        - name: {{ .Values.operator.imageRepository.credentialsSecretName }}
{{- end }}
      containers:
        - command: ["/kurrentdb-operator"]
          image: {{ include "operator.image.qualifiedName" . }}
          name: controller
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          env:
            - name: XDG_CONFIG_HOME
              value: /tmp/workspace/helm/.config
            - name: XDG_CACHE_HOME
              value: /tmp/workspace/helm/.cache
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config
              mountPath: config.yaml
              subPath: config.yaml
            - name: workspace
              mountPath: /tmp/workspace
          ports:
            - containerPort: 18080
              name: http-web-svc
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              memory: {{ .Values.operator.resources.limits.memory }}
            requests:
              cpu: {{ .Values.operator.resources.requests.cpu }}
              memory: {{ .Values.operator.resources.requests.memory }}
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: kurrentdb-operator
        - name: workspace
          emptyDir: {}
      serviceAccountName: kurrentdb-operator
      terminationGracePeriodSeconds: 10
