{{- if dig "license" "key" false .Values.operator -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.operator.license.secretName | default "operator-license" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/created-by: kurrent
    app.kubernetes.io/part-of: kurrentdb-operator
type: Opaque
data:
  licenseKey: {{ .Values.operator.license.key | b64enc }}
  licenseFile: {{ .Values.operator.license.file | b64enc }}
{{- end }}
{{- if dig "imageRepository" "username" false .Values.operator }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.operator.imageRepository.credentialsSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/created-by: kurrent
    app.kubernetes.io/part-of: kurrentdb-operator
type: kubernetes.io/dockerconfigjson
data:
  username: {{ .Values.operator.imageRepository.username | b64enc }}
  password: {{ .Values.operator.imageRepository.password | b64enc }}
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"username\": \"%s\", \"password\": \"%s\", \"email\": \"user@somewhere.com\", \"auth\": \"%s\"}}}" .Values.operator.imageRepository.url .Values.operator.imageRepository.username .Values.operator.imageRepository.password (printf "%s:%s" .Values.operator.imageRepository.username .Values.operator.imageRepository.password | b64enc) | b64enc | quote }}
{{- end }}
