apiVersion: v2
name: cluster-setup
description: A Helm chart for Kubernetes to quickly setup necessary resources
type: application
version: 1.2.0
icon: https://raw.githubusercontent.com/jamesw-xml/cluster-setup-helm-chart/refs/heads/main/main/profile.jpg
home: https://github.com/jamesw-xml/cluster-setup-helm-chart
appVersion: "1.16.0"
dependencies:
  - name: argo-cd
    version: 8.0.9
    repository: https://argoproj.github.io/argo-helm
    condition: argo-cd.enabled
  - name: cert-manager
    version: 1.17.2
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled


