# Default values for cluster-setup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Add extra secrets here if needed
secrets: []
  # - name: mysecret
  #   type: Opaque
  #   data:
  #     EVENTSTORE_INSECURE: "true"  # Set to true to enable insecure mode for KurrentDB
  #     EVENTSTORE_ADMIN_PASSWORD: "Y2hhbmdlYXQ="  # Base64 encoded 'changeit'

storageClasses:
  - name: default
    provisioner: rancher.io/local-path
    volumeBindingMode: WaitForFirstConsumer
    reclaimPolicy: Retain
    allowVolumeExpansion: true


argo-cd:
  enabled: true
  crds:
    keep: false
  controller:
    replicas: 1
  namespaceOverride: argocd
  fullnameOverride: argocd
  configs:
    cm:
      exec.enabled: true
    secret:
      argocdServerAdminPassword: $2b$12$/A8aEgy54C65WT9oYmADQu9orYjK5J09nJfEg2UguuV9NBHcC5xQW # password defaults to admin
  server:
    insecure: true
    service:
      type: LoadBalancer
      port: 80
      targetPort: 8080

cert-manager:
  enabled: true
  crds:
    enabled: true
    keep: false
  ingressShim:
    defaultIssuerName: letsencrypt-prod
    defaultIssuerKind: ClusterIssuer

apisix:
  enabled: true
  namespace: ingress-apisix
  namespaceOverride: ingress-apisix
  applicationValues:
      apisix:
        enabled: true
        prometheus:
          enabled: true
        ssl:
          enabled: true
      service:
        type: LoadBalancer
        # annotations:
        #   service.beta.kubernetes.io/azure-load-balancer-internal: "true"        
        #   service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "subnet-dev-spoke04"        
        # loadBalancerIp: 10.43.0.10
      gateway:
        type: LoadBalancer
        tls:
          enabled: true
          servicePort: 443
          containerPort: 9443

      admin:
        enabled: true

      dashboard:
        enabled: true

      ingress-controller:
        enabled: true
        config:
          apisix:
            serviceNamespace: ingress-apisix
            adminAPIVersion: "v3"
      etcd:
        persistence:
          enabled: true
          storageClass: default
          size: 10Gi
          accessModes:
            - ReadWriteOnce

kurrentdb:
  enabled: true
  namespace: kurrentdb
  image:
    repository: docker.kurrent.io/kurrent-latest/kurrentdb
    tag: latest
    pullPolicy: IfNotPresent
  insecure: true  # set to true to enable EVENTSTORE_INSECURE
  resources:
    requests:
      cpu: "400m"
      memory: "2Gi"
    limits:
      cpu: "500m"
      memory: "3Gi"
  pvc:
    name: pvc-eventstore
    storage: 20Gi
    storageClassName: default
  secretName: mysecret
  adminPasswordKey: changeit


kube-prometheus-stack:
  enabled: true
  namespaceOverride: monitoring
  applicationValues:
    namespaceOverride: monitoring
    grafana:
      persistence: 
        enabled: true
        storageClassName: default
        accessModes:
          - ReadWriteOnce
        size: 10Gi
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
              storageClassName: default
elasticstack:
  enabled: true
  namespaceOverride: elasticsearch
  persistence:
    enabled: true
    storageClass: default
    accessModes: ["ReadWriteOnce"]
    size: 30Gi
  elasticsearch:
    version: 7.17.7
    nodesets:
      - name: default
        podTemplate:
            spec:
              containers:
                - name: elasticsearch
                  resources:
                    requests:
                      cpu: "500m"
                      memory: "2Gi"
                    limits:
                      cpu: "1"
                      memory: "4Gi"
            
  kibana:
    version: 7.17.7
