{{- range .Values.storageClasses }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
provisioner: {{ .provisioner }}
volumeBindingMode: {{ .volumeBindingMode | default "WaitForFirstConsumer" }}
{{- if .parameters }}
parameters:
{{ toYaml .parameters | indent 2 }}
{{- end }}
reclaimPolicy: {{ .reclaimPolicy | default "Retain" }}
allowVolumeExpansion: {{ .allowVolumeExpansion | default true }}
---
{{- end }}