{{- if (index .Values "argo-cd").enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ (index .Values "argo-cd").namespaceOverride }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
---
{{- end }}

{{- if .Values.kurrentdb.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.kurrentdb.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end }}

{{- if .Values.elasticstack.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.elasticstack.namespaceOverride | default "elastic" }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end }}