---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: kurrentdb-operator
  name: kurrentdb-license
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kurrentdb-license
subjects:
- kind: ServiceAccount
  name: kurrentdb-operator
  namespace: {{ .Release.Namespace }}
{{ $kind := ternary "ClusterRoleBinding" "RoleBinding" (not .Values.operator.namespaces) -}}
{{- $refKind := ternary "ClusterRole" "Role" (not .Values.operator.namespaces) -}}
{{- /* If no namespaces are defined, run the loop once with an empty namespace */ -}}
{{- range $index, $namespace := default (tuple "") .Values.operator.namespaces -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $kind }}
metadata:
  labels:
    app.kubernetes.io/name: kurrentdb-operator
  name: kurrentdb-operator
{{- if $namespace }}
  namespace: {{ $namespace }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ $refKind }}
  name: kurrentdb-operator
subjects:
- kind: ServiceAccount
  name: kurrentdb-operator
  namespace: {{ $.Release.Namespace }}
{{ end }}
