---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kurrentdb-license
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
{{ $kind := ternary "ClusterRole" "Role" (not .Values.operator.namespaces) -}}
{{- /* If no namespaces are defined, run the loop once with an empty namespace */ -}}
{{- range $index, $namespace := default (tuple "") .Values.operator.namespaces -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $kind }}
metadata:
  name: kurrentdb-operator
{{- if $namespace }}
  namespace: {{ $namespace }}
{{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "events.k8s.io"
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetes.kurrent.io
  resources:
  - kurrentdbbackups
  - kurrentdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetes.kurrent.io
  resources:
  - kurrentdbbackups/finalizers
  - kurrentdbs/finalizers
  verbs:
  - update
- apiGroups:
  - kubernetes.kurrent.io
  resources:
  - kurrentdbbackups/status
  - kurrentdbs/status
  verbs:
  - get
  - patch
  - update
{{ end }}
