crds:
  enabled: true
operator:
  resources:
    requests:
      memory: 64Mi
      cpu: 1000m
    limits:
      memory: 128Mi
  imageRepository:
    name: cloudsmith
    url: docker.kurrent.io/kurrent-latest
    credentialsSecretName: kurrent-image-repo-credentials
    username:
    password:
  image:
    name: "kurrentdb-operator:1.1.0"
    pullPolicy: IfNotPresent
  logging:
    level: info
  namespaces: []
  license:
    secretName: operator-license
