apiVersion: v2
name: cluster-setup
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.16.0"
dependencies:
  - name: argo-cd
    version: 8.0.9
    condition: argo-cd.enabled
  - name: cert-manager
    version: 1.17.2
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
  - name: kurrentdb-operator
    version: 1.1.0
    condition: kurrentdb.enabled


