apiVersion: v2
name: cluster-setup
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.16.0"
dependencies:
  - name: argo-cd
    version: 8.0.9
    repository: https://argoproj.github.io/argo-helm
    condition: argo-cd.enabled
  - name: cert-manager
    version: 1.17.2
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
  - name: apisix-ingress-controller
    version: 0.14.0
    repository: https://charts.apiseven.com
    condition: apisix.enabled


