apiVersion: v1
entries:
  cluster-setup:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-05-24T17:12:37.529805+01:00"
    dependencies:
    - condition: argo-cd.enabled
      name: argo-cd
      repository: https://argoproj.github.io/argo-helm
      version: 8.0.9
    - condition: cert-manager.enabled
      name: cert-manager
      repository: https://charts.jetstack.io
      version: 1.17.2
    description: A Helm chart for Kubernetes
    digest: 6998fed5f80e02692deac0dfe19deade4dd9f28c1cd166d529b00605f31ae5d7
    name: cluster-setup
    type: application
    urls:
    - https://jamesw-xml.github.io/cluster-setup-helm-chart/charts/cluster-setup-1.0.0.tgz
    version: 1.0.0
generated: "2025-05-24T17:12:37.5188052+01:00"
